version: '3.8'

services:
  # Incoming request and trigger php interpreter
  server:
    image: 'nginx-stable:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # Running and exec php code
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # Delegated is used for performance optimization
  # Database
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env
  # Package Manager for creating laravel
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # #Supporting containers
  # artisan:
  # npm:
